# Generated by Django 3.1.1 on 2020-10-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('dataLancamento', models.IntegerField()),
                ('motor', models.CharField(max_length=64)),
                ('plataformas', models.CharField(max_length=64)),
                ('projetistas', models.CharField(max_length=64)),
                ('desenvolvedores', models.CharField(max_length=64)),
                ('generos', models.CharField(max_length=64)),
            ],
        ),
    ]
