# Generated by Django 3.1.1 on 2020-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='jogos',
            old_name='desenvolvedores',
            new_name='desenvolvedor',
        ),
        migrations.RenameField(
            model_name='jogos',
            old_name='generos',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='jogos',
            old_name='plataformas',
            new_name='plataforma',
        ),
        migrations.RenameField(
            model_name='jogos',
            old_name='projetistas',
            new_name='projetista',
        ),
    ]
