# Generated by Django 3.1.1 on 2020-10-29 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_jogos_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='games.generos'),
        ),
    ]
