# Generated by Django 3.1.1 on 2020-10-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20201029_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generos',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='generos', to='games.Jogos'),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='dataLancamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='projetista',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='plataformas',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='plataformas', to='games.Jogos'),
        ),
    ]
