# Generated by Django 3.1.1 on 2020-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20201029_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='fotos', to='games.Jogos'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='generos', to='games.Jogos'),
        ),
        migrations.AlterField(
            model_name='plataformas',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='plataformas', to='games.Jogos'),
        ),
    ]
