# Generated by Django 3.1.1 on 2020-10-30 16:46

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20201030_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(upload_to=games.models.Jogos),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='fotos', to='games.Jogos'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='generos', to='games.Jogos'),
        ),
        migrations.AlterField(
            model_name='plataformas',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='plataformas', to='games.Jogos'),
        ),
    ]
