# Generated by Django 3.1.1 on 2020-11-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20201104_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterField(
            model_name='generos',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='generos', to='games.Jogos'),
        ),
        migrations.AlterField(
            model_name='plataformas',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='plataformas', to='games.Jogos'),
        ),
    ]
